<?php
$customerId     = $this->getRequest()->getParam('id');

$model		= Mage::getModel('reward/reward');
$model		= $model->getCollection()
->addFieldToFilter('customer_id',array($customerId))
->getData();

$redemptionAmount	= 0;
for($q=0;$q<count($model);$q++)
{
	$redemptionAmount	+= $model[$q]['redemption_amount'];
}
?>
<div id="customer_info_tabs_customer_edit_tab_action_content">
	<div class="entry-edit">
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend">Redemption Amount</h4>
		</div>
		<div id="group_fields4" class="fieldset fieldset-wide">
			<div class="hor-scroll">
				<table class="form-list" cellspacing="0">
					<tbody>
						<tr>
							<td class="label"><?php echo $this->__('Redemption Price')?></td>
							<td class="value"><input type="text" class="input-text" id="redemption_id" name="redemption_id" value="<?php echo $redemptionAmount;?>" /></td>
						</tr>
					</tbody>
				</table>

			</div>
		</div>
	</div>
</div>
